backend:
  name: git-gateway
  branch: main

media_folder: "public/assets"
public_folder: "/assets"

collections:
  - name: "products"
    label: "Products"
    folder: "public/content/products"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - {label: "ID", name: "id", widget: "number"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "Category", name: "category", widget: "select", options: ["Dresses", "Sets", "Streetwear"]}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Gallery Images", name: "images", widget: "list", field: {label: "Image", name: "url", widget: "image"}}
